site_name: arcus docs
theme: 
   name: 'material'
   feature:
      tabs: true
   
docs_dir: docs
site_dir: site
repo_name: 'naver/arcus'
repo_url: 'https://github.com/naver/arcus'

plugins:
   - awesome-pages
   - search