site_name: 'ARCUS Documentation'
theme: 
   name: 'material'
   logo: 'images/logo.png'
   feature:
      tabs: true
   
docs_dir: docs
site_dir: site
repo_name: 'naver/arcus'
repo_url: 'https://github.com/naver/arcus'
edit_uri: ''

plugins:
   - awesome-pages
   - search